/*
 * Conference Session Tracker - APEX Application
 * Generated for: Building APEX Without the Builder Demo
 * Description: Complete APEX application created via API (no Builder used!)
 * 
 * AI Model: Claude Sonnet 4.5
 * Generation Date: 2025-11-01
 * 
 * IMPORTANT: This entire application was generated by AI and deployed
 * without ever opening the APEX Builder interface!
 */

SET SERVEROUTPUT ON
SET DEFINE OFF
SET VERIFY OFF

PROMPT ========================================
PROMPT Creating APEX Application via API
PROMPT ========================================
PROMPT
PROMPT *** NO APEX BUILDER REQUIRED ***
PROMPT This application is created entirely through PL/SQL API calls
PROMPT ========================================

-- Set workspace and application settings
BEGIN
    apex_application_install.set_workspace('YOUR_WORKSPACE');
    apex_application_install.set_application_id(200);
    apex_application_install.set_schema('YOUR_SCHEMA');
    apex_application_install.set_application_alias('CONF_TRACKER');
END;
/

-- ============================================================================
-- Create Application
-- ============================================================================
PROMPT
PROMPT Creating application shell...

BEGIN
    -- Remove existing application if it exists
    BEGIN
        apex_application_admin.remove_application(p_application_id => 200);
    EXCEPTION
        WHEN OTHERS THEN NULL;
    END;
    
    -- Create new application
    wwv_flow_api.create_flow(
        p_id                      => 200,
        p_owner                   => 'YOUR_SCHEMA',
        p_name                    => 'Conference Session Tracker',
        p_alias                   => 'CONF_TRACKER',
        p_application_group       => 'Demo Applications',
        p_page_view_logging       => 'YES',
        p_page_protection_enabled_y_n => 'Y',
        p_checksum_salt_last_reset => TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
        p_bookmark_checksum_function => 'SH512',
        p_compatibility_mode      => '21.2',
        p_flow_language           => 'en',
        p_flow_language_derived_from => 'FLOW_PRIMARY_LANGUAGE',
        p_date_format             => 'DS',
        p_timestamp_format        => 'DS',
        p_date_time_format        => 'DS',
        p_direction_right_to_left => 'N',
        p_flow_image_prefix       => '',
        p_authentication_id       => wwv_flow_api.id(0),  -- Using default
        p_application_tab_set     => 0,
        p_logo_type               => 'T',
        p_logo_text               => 'Conference Session Tracker',
        p_proxy_server            => '',
        p_no_proxy_domains        => '',
        p_flow_version            => 'Release 1.0',
        p_flow_status             => 'AVAILABLE_W_EDIT_LINK',
        p_flow_unavailable_text   => 'This application is currently unavailable.',
        p_exact_substitutions_only => 'Y',
        p_browser_cache           => 'N',
        p_browser_frame           => 'D',
        p_rejoin_existing_sessions => 'N',
        p_csv_encoding            => 'Y',
        p_auto_time_zone          => 'N',
        p_substitution_string_01  => 'APP_NAME',
        p_substitution_value_01   => 'Conference Session Tracker',
        p_last_updated_by         => 'AI_GENERATED',
        p_last_upd_yyyymmddhh24miss => TO_CHAR(SYSDATE, 'YYYYMMDDHH24MISS'),
        p_file_prefix             => '#APEX_FILES#',
        p_files_version           => 1,
        p_ui_type_name            => 'DESKTOP',
        p_print_server_type       => 'NATIVE',
        p_is_pwa                  => 'N',
        p_pwa_is_installable      => 'N');
END;
/

PROMPT Application created: ID = 200

-- ============================================================================
-- Page 0: Global Page
-- ============================================================================
PROMPT Creating Page 0 (Global Page)...

BEGIN
    wwv_flow_api.create_page(
        p_id         => 0,
        p_flow_id    => 200,
        p_name       => 'Global Page',
        p_alias      => 'GLOBAL_PAGE',
        p_step_title => 'Global Page');
END;
/

-- ============================================================================
-- Page 1: Dashboard
-- ============================================================================
PROMPT Creating Page 1 (Dashboard)...

BEGIN
    wwv_flow_api.create_page(
        p_id              => 1,
        p_flow_id         => 200,
        p_name            => 'Dashboard',
        p_alias           => 'DASHBOARD',
        p_step_title      => 'Conference Dashboard',
        p_autocomplete_on_off => 'OFF',
        p_page_template_options => '#DEFAULT#',
        p_protection_level => 'C',
        p_help_text       => 'Real-time conference dashboard showing today''s sessions and key metrics.');
        
    -- Region: Today's Sessions
    wwv_flow_api.create_page_plug(
        p_id                  => wwv_flow_api.id('TODAY_SESSIONS'),
        p_flow_id             => 200,
        p_page_id             => 1,
        p_plug_name           => 'Today''s Sessions',
        p_region_template_options => '#DEFAULT#:t-Region--scrollBody',
        p_plug_template       => wwv_flow_api.id(0),  -- Standard region
        p_plug_display_sequence => 10,
        p_plug_display_point  => 'REGION_POSITION_01',
        p_query_type          => 'SQL',
        p_plug_source         => q'[
SELECT 
    s.session_id,
    s.title,
    s.session_code,
    TO_CHAR(s.start_time, 'HH24:MI') as start_time,
    TO_CHAR(s.end_time, 'HH24:MI') as end_time,
    sp.first_name || ' ' || sp.last_name as speaker,
    r.room_name,
    r.capacity as room_capacity,
    conference_pkg.get_session_occupancy(s.session_id) as registered,
    s.max_attendees,
    CASE 
        WHEN s.max_attendees IS NULL THEN 'No Limit'
        WHEN conference_pkg.get_session_occupancy(s.session_id) >= s.max_attendees THEN 'FULL'
        ELSE TO_CHAR(s.max_attendees - conference_pkg.get_session_occupancy(s.session_id)) || ' spots left'
    END as availability,
    s.track,
    s.level
FROM sessions s
JOIN speakers sp ON s.speaker_id = sp.speaker_id
JOIN rooms r ON s.room_id = r.room_id
WHERE TRUNC(s.session_date) = TRUNC(SYSDATE)
AND s.status != 'CANCELLED'
ORDER BY s.start_time, r.room_name
        ]',
        p_plug_source_type    => 'NATIVE_CARDS',
        p_plug_query_options  => 'DERIVED_REPORT_COLUMNS',
        p_plug_query_show_nulls_as => '-');
        
    -- Region: Statistics
    wwv_flow_api.create_page_plug(
        p_id                  => wwv_flow_api.id('STATS'),
        p_flow_id             => 200,
        p_page_id             => 1,
        p_plug_name           => 'Conference Statistics',
        p_region_template_options => '#DEFAULT#:t-Region--noPadding:t-Region--scrollBody',
        p_plug_template       => wwv_flow_api.id(0),
        p_plug_display_sequence => 20,
        p_plug_display_point  => 'REGION_POSITION_02',
        p_query_type          => 'SQL',
        p_plug_source         => q'[
SELECT 
    (SELECT COUNT(*) FROM sessions WHERE status != 'CANCELLED') as total_sessions,
    (SELECT COUNT(*) FROM sessions WHERE TRUNC(session_date) = TRUNC(SYSDATE)) as today_sessions,
    (SELECT COUNT(*) FROM speakers) as total_speakers,
    (SELECT COUNT(*) FROM attendees WHERE status = 'CHECKED_IN') as checked_in_attendees,
    (SELECT SUM(capacity) FROM rooms WHERE is_active = 'Y') as total_capacity
FROM dual
        ]',
        p_plug_source_type    => 'NATIVE_HTML_REGIONS');
        
    -- Region: Session by Track Chart
    wwv_flow_api.create_page_plug(
        p_id                  => wwv_flow_api.id('TRACK_CHART'),
        p_flow_id             => 200,
        p_page_id             => 1,
        p_plug_name           => 'Sessions by Track',
        p_region_template_options => '#DEFAULT#:t-Region--scrollBody',
        p_plug_template       => wwv_flow_api.id(0),
        p_plug_display_sequence => 30,
        p_plug_display_point  => 'REGION_POSITION_03',
        p_query_type          => 'SQL',
        p_plug_source         => q'[
SELECT 
    track as label,
    COUNT(*) as value
FROM sessions
WHERE status != 'CANCELLED'
GROUP BY track
ORDER BY COUNT(*) DESC
        ]',
        p_plug_source_type    => 'NATIVE_JET_CHART');
        
END;
/

-- ============================================================================
-- Page 10: Session Catalog (Interactive Report)
-- ============================================================================
PROMPT Creating Page 10 (Session Catalog)...

BEGIN
    wwv_flow_api.create_page(
        p_id              => 10,
        p_flow_id         => 200,
        p_name            => 'Session Catalog',
        p_alias           => 'SESSION_CATALOG',
        p_step_title      => 'Session Catalog',
        p_autocomplete_on_off => 'OFF',
        p_page_template_options => '#DEFAULT#',
        p_protection_level => 'C',
        p_help_text       => 'Browse and search all conference sessions.');
        
    -- Interactive Report Region
    wwv_flow_api.create_page_plug(
        p_id                  => wwv_flow_api.id('SESSION_IR'),
        p_flow_id             => 200,
        p_page_id             => 10,
        p_plug_name           => 'Sessions',
        p_region_template_options => '#DEFAULT#:t-Region--noPadding:t-Region--scrollBody',
        p_plug_template       => wwv_flow_api.id(0),
        p_plug_display_sequence => 10,
        p_plug_display_point  => 'BODY',
        p_query_type          => 'SQL',
        p_plug_source         => q'[
SELECT 
    s.session_id,
    s.session_code,
    s.title,
    SUBSTR(s.description, 1, 200) || 
        CASE WHEN LENGTH(s.description) > 200 THEN '...' ELSE '' END as description_preview,
    TO_CHAR(s.session_date, 'Day, DD-MON-YYYY') as session_date_display,
    TO_CHAR(s.start_time, 'HH24:MI') || ' - ' || TO_CHAR(s.end_time, 'HH24:MI') as time_slot,
    sp.first_name || ' ' || sp.last_name as speaker,
    sp.company as speaker_company,
    r.room_name,
    r.building,
    s.track,
    s.level,
    conference_pkg.get_session_occupancy(s.session_id) as registered_count,
    s.max_attendees,
    CASE 
        WHEN s.max_attendees IS NULL THEN 
            '<span class="u-success-text">No Limit</span>'
        WHEN conference_pkg.get_session_occupancy(s.session_id) >= s.max_attendees THEN 
            '<span class="u-danger-text">FULL</span>'
        WHEN conference_pkg.get_session_occupancy(s.session_id) >= (s.max_attendees * 0.8) THEN 
            '<span class="u-warning-text">Nearly Full</span>'
        ELSE 
            '<span class="u-success-text">Available</span>'
    END as status_display,
    s.status,
    s.start_time,
    s.session_date
FROM sessions s
JOIN speakers sp ON s.speaker_id = sp.speaker_id
JOIN rooms r ON s.room_id = r.room_id
WHERE s.status != 'CANCELLED'
ORDER BY s.session_date, s.start_time
        ]',
        p_plug_source_type    => 'NATIVE_IR',
        p_plug_query_options  => 'DERIVED_REPORT_COLUMNS');
        
    -- Add Create Session button
    wwv_flow_api.create_page_button(
        p_id              => wwv_flow_api.id('CREATE_SESSION'),
        p_flow_id         => 200,
        p_page_id         => 10,
        p_button_sequence => 10,
        p_button_plug_id  => wwv_flow_api.id('SESSION_IR'),
        p_button_name     => 'CREATE_SESSION',
        p_button_action   => 'REDIRECT_PAGE',
        p_button_template_options => '#DEFAULT#:t-Button--iconLeft',
        p_button_template_id => wwv_flow_api.id(0),
        p_button_is_hot   => 'Y',
        p_button_image_alt => 'Create Session',
        p_button_position => 'RIGHT_OF_IR_SEARCH_BAR',
        p_button_redirect_url => 'f?p=&APP_ID.:20:&SESSION.::&DEBUG.:20::',
        p_icon_css_classes => 'fa-plus');
        
END;
/

-- ============================================================================
-- Page 20: Session Form (Modal)
-- ============================================================================
PROMPT Creating Page 20 (Session Form)...

BEGIN
    wwv_flow_api.create_page(
        p_id              => 20,
        p_flow_id         => 200,
        p_name            => 'Session Form',
        p_alias           => 'SESSION_FORM',
        p_step_title      => 'Session',
        p_autocomplete_on_off => 'OFF',
        p_page_mode       => 'MODAL',
        p_page_template_options => '#DEFAULT#',
        p_protection_level => 'C',
        p_help_text       => 'Create or edit a conference session.');
        
    -- Form Region
    wwv_flow_api.create_page_plug(
        p_id                  => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_flow_id             => 200,
        p_page_id             => 20,
        p_plug_name           => 'Session Details',
        p_region_template_options => '#DEFAULT#',
        p_plug_template       => wwv_flow_api.id(0),
        p_plug_display_sequence => 10,
        p_plug_display_point  => 'BODY',
        p_query_type          => 'TABLE',
        p_query_table         => 'SESSIONS',
        p_plug_source_type    => 'NATIVE_FORM');
        
    -- Form Items
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_SESSION_ID'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_SESSION_ID',
        p_source_data_type => 'NUMBER',
        p_is_primary_key  => 'Y',
        p_item_sequence   => 10,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_source          => 'SESSION_ID',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_HIDDEN',
        p_protection_level => 'S');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_TITLE'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_TITLE',
        p_source_data_type => 'VARCHAR2',
        p_item_sequence   => 20,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Session Title',
        p_source          => 'TITLE',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_TEXT_FIELD',
        p_cSize           => 60,
        p_cMaxlength      => 200,
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#',
        p_is_required     => 'Y');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_SESSION_CODE'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_SESSION_CODE',
        p_source_data_type => 'VARCHAR2',
        p_item_sequence   => 30,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Session Code',
        p_source          => 'SESSION_CODE',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_TEXT_FIELD',
        p_cSize           => 20,
        p_cMaxlength      => 20,
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#',
        p_help_text       => 'Unique session identifier (e.g., S101, WS205)');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_DESCRIPTION'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_DESCRIPTION',
        p_source_data_type => 'CLOB',
        p_item_sequence   => 40,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Description',
        p_source          => 'DESCRIPTION',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_TEXTAREA',
        p_cSize           => 60,
        p_cHeight         => 4,
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_SESSION_DATE'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_SESSION_DATE',
        p_source_data_type => 'DATE',
        p_item_sequence   => 50,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Session Date',
        p_format_mask     => 'DD-MON-YYYY',
        p_source          => 'SESSION_DATE',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_DATE_PICKER',
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#',
        p_is_required     => 'Y');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_START_TIME'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_START_TIME',
        p_source_data_type => 'TIMESTAMP',
        p_item_sequence   => 60,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Start Time',
        p_format_mask     => 'DD-MON-YYYY HH24:MI',
        p_source          => 'START_TIME',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_DATE_PICKER',
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#',
        p_is_required     => 'Y');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_END_TIME'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_END_TIME',
        p_source_data_type => 'TIMESTAMP',
        p_item_sequence   => 70,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'End Time',
        p_format_mask     => 'DD-MON-YYYY HH24:MI',
        p_source          => 'END_TIME',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_DATE_PICKER',
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#',
        p_is_required     => 'Y');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_ROOM_ID'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_ROOM_ID',
        p_source_data_type => 'NUMBER',
        p_item_sequence   => 80,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Room',
        p_source          => 'ROOM_ID',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_SELECT_LIST',
        p_lov             => 'SELECT room_name || '' (Capacity: '' || capacity || '')'' d, room_id r FROM rooms WHERE is_active = ''Y'' ORDER BY room_name',
        p_lov_display_null => 'Y',
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#',
        p_is_required     => 'Y');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_SPEAKER_ID'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_SPEAKER_ID',
        p_source_data_type => 'NUMBER',
        p_item_sequence   => 90,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Speaker',
        p_source          => 'SPEAKER_ID',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_SELECT_LIST',
        p_lov             => 'SELECT first_name || '' '' || last_name || '' ('' || company || '')'' d, speaker_id r FROM speakers WHERE is_active = ''Y'' ORDER BY last_name, first_name',
        p_lov_display_null => 'Y',
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#',
        p_is_required     => 'Y');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_TRACK'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_TRACK',
        p_source_data_type => 'VARCHAR2',
        p_item_sequence   => 100,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Track',
        p_source          => 'TRACK',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_SELECT_LIST',
        p_lov             => 'STATIC:Technical;TECHNICAL,Business;BUSINESS,Community;COMMUNITY,Keynote;KEYNOTE',
        p_lov_display_null => 'Y',
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_LEVEL'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_LEVEL',
        p_source_data_type => 'VARCHAR2',
        p_item_sequence   => 110,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Level',
        p_source          => 'LEVEL',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_SELECT_LIST',
        p_lov             => 'STATIC:All Levels;ALL,Beginner;BEGINNER,Intermediate;INTERMEDIATE,Advanced;ADVANCED',
        p_lov_display_null => 'Y',
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_MAX_ATTENDEES'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_MAX_ATTENDEES',
        p_source_data_type => 'NUMBER',
        p_item_sequence   => 120,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Max Attendees',
        p_source          => 'MAX_ATTENDEES',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_NUMBER_FIELD',
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#',
        p_help_text       => 'Leave blank for unlimited capacity');
        
    wwv_flow_api.create_page_item(
        p_id              => wwv_flow_api.id('P20_STATUS'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_name            => 'P20_STATUS',
        p_source_data_type => 'VARCHAR2',
        p_item_sequence   => 130,
        p_item_plug_id    => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_use_cache_before_default => 'NO',
        p_prompt          => 'Status',
        p_source          => 'STATUS',
        p_source_type     => 'DB_COLUMN',
        p_display_as      => 'NATIVE_SELECT_LIST',
        p_lov             => 'STATIC:Scheduled;SCHEDULED,Confirmed;CONFIRMED,Cancelled;CANCELLED,Completed;COMPLETED',
        p_lov_display_null => 'N',
        p_field_template  => wwv_flow_api.id(0),
        p_item_template_options => '#DEFAULT#',
        p_is_required     => 'Y');
        
    -- Buttons
    wwv_flow_api.create_page_button(
        p_id              => wwv_flow_api.id('CANCEL'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_button_sequence => 10,
        p_button_plug_id  => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_button_name     => 'CANCEL',
        p_button_action   => 'DEFINED_BY_DA',
        p_button_template_options => '#DEFAULT#',
        p_button_template_id => wwv_flow_api.id(0),
        p_button_image_alt => 'Cancel',
        p_button_position => 'REGION_TEMPLATE_CLOSE');
        
    wwv_flow_api.create_page_button(
        p_id              => wwv_flow_api.id('DELETE'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_button_sequence => 20,
        p_button_plug_id  => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_button_name     => 'DELETE',
        p_button_action   => 'SUBMIT',
        p_button_template_options => '#DEFAULT#:t-Button--danger',
        p_button_template_id => wwv_flow_api.id(0),
        p_button_image_alt => 'Delete',
        p_button_position => 'REGION_TEMPLATE_DELETE',
        p_button_condition => 'P20_SESSION_ID',
        p_button_condition_type => 'ITEM_IS_NOT_NULL',
        p_database_action => 'DELETE');
        
    wwv_flow_api.create_page_button(
        p_id              => wwv_flow_api.id('SAVE'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_button_sequence => 30,
        p_button_plug_id  => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_button_name     => 'SAVE',
        p_button_action   => 'SUBMIT',
        p_button_template_options => '#DEFAULT#:t-Button--gapLeft',
        p_button_template_id => wwv_flow_api.id(0),
        p_button_is_hot   => 'Y',
        p_button_image_alt => 'Save',
        p_button_position => 'REGION_TEMPLATE_CREATE',
        p_button_condition => 'P20_SESSION_ID',
        p_button_condition_type => 'ITEM_IS_NOT_NULL',
        p_database_action => 'UPDATE');
        
    wwv_flow_api.create_page_button(
        p_id              => wwv_flow_api.id('CREATE'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_button_sequence => 40,
        p_button_plug_id  => wwv_flow_api.id('SESSION_FORM_REGION'),
        p_button_name     => 'CREATE',
        p_button_action   => 'SUBMIT',
        p_button_template_options => '#DEFAULT#:t-Button--gapLeft',
        p_button_template_id => wwv_flow_api.id(0),
        p_button_is_hot   => 'Y',
        p_button_image_alt => 'Create',
        p_button_position => 'REGION_TEMPLATE_CREATE',
        p_button_condition => 'P20_SESSION_ID',
        p_button_condition_type => 'ITEM_IS_NULL',
        p_database_action => 'INSERT');
        
    -- Form Processing
    wwv_flow_api.create_page_process(
        p_id              => wwv_flow_api.id('PROCESS_SESSION'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_process_sequence => 10,
        p_process_point   => 'PROCESSING',
        p_process_type    => 'NATIVE_FORM_DML',
        p_process_name    => 'Process Session',
        p_attribute_01    => 'SESSIONS',
        p_error_display_location => 'INLINE_IN_NOTIFICATION',
        p_process_success_message => 'Session saved successfully.');
        
    wwv_flow_api.create_page_process(
        p_id              => wwv_flow_api.id('CLOSE_DIALOG'),
        p_flow_id         => 200,
        p_page_id         => 20,
        p_process_sequence => 20,
        p_process_point   => 'PROCESSING',
        p_process_type    => 'NATIVE_CLOSE_WINDOW',
        p_process_name    => 'Close Dialog',
        p_error_display_location => 'INLINE_IN_NOTIFICATION');
        
END;
/

PROMPT ========================================
PROMPT APEX Application Created Successfully!
PROMPT ========================================
PROMPT
PROMPT Application ID: 200
PROMPT Application Alias: CONF_TRACKER
PROMPT Pages Created: 
PROMPT   - Page 0: Global Page
PROMPT   - Page 1: Dashboard
PROMPT   - Page 10: Session Catalog
PROMPT   - Page 20: Session Form
PROMPT
PROMPT *** THIS APPLICATION WAS CREATED ENTIRELY BY AI ***
PROMPT *** WITHOUT OPENING THE APEX BUILDER ***
PROMPT
PROMPT Next Steps:
PROMPT 1. Access the application at: [Your APEX URL]/r/conf_tracker
PROMPT 2. (Optional) Open Builder to see what was created
PROMPT 3. Run 05-ratings-feature.sql for the live demo addition
PROMPT ========================================

COMMIT;
