/*
 * Conference Session Tracker - Session Ratings Feature
 * Generated for: Building APEX Without the Builder Demo
 * Description: Add-on feature to demonstrate live AI-driven development
 * 
 * AI Model: Claude Sonnet 4.5
 * Generation Date: 2025-11-01
 * 
 * PURPOSE: This script will be run LIVE during the demo to show how
 * quickly new features can be added using AI-generated code!
 */

SET SERVEROUTPUT ON
SET DEFINE OFF

PROMPT ========================================
PROMPT Adding Session Ratings Feature
PROMPT ========================================
PROMPT
PROMPT This is a LIVE DEMO of adding a new feature!
PROMPT Requested by: Conference attendees
PROMPT Generated by: AI in real-time
PROMPT ========================================

-- ============================================================================
-- Create Session Ratings Table
-- ============================================================================
PROMPT
PROMPT Creating ratings table...

CREATE TABLE session_ratings (
    rating_id           NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    session_id          NUMBER NOT NULL,
    attendee_id         NUMBER NOT NULL,
    rating              NUMBER(1) NOT NULL CHECK (rating BETWEEN 1 AND 5),
    comment             VARCHAR2(1000),
    would_recommend     VARCHAR2(1) DEFAULT 'Y' CHECK (would_recommend IN ('Y', 'N')),
    rating_date         DATE DEFAULT SYSDATE NOT NULL,
    CONSTRAINT fk_rating_session FOREIGN KEY (session_id) REFERENCES sessions(session_id) ON DELETE CASCADE,
    CONSTRAINT fk_rating_attendee FOREIGN KEY (attendee_id) REFERENCES attendees(attendee_id) ON DELETE CASCADE,
    CONSTRAINT uk_rating_session_attendee UNIQUE (session_id, attendee_id)
);

COMMENT ON TABLE session_ratings IS 'Attendee ratings and feedback for sessions';
COMMENT ON COLUMN session_ratings.rating IS 'Rating from 1 (poor) to 5 (excellent)';
COMMENT ON COLUMN session_ratings.would_recommend IS 'Would the attendee recommend this session?';

CREATE INDEX idx_rating_session ON session_ratings(session_id);
CREATE INDEX idx_rating_attendee ON session_ratings(attendee_id);

PROMPT   ... ratings table created

-- ============================================================================
-- Add Rating Functions to Package
-- ============================================================================
PROMPT
PROMPT Extending conference_pkg with rating functions...

CREATE OR REPLACE PACKAGE conference_pkg AS
    
    -- Existing functions (declarations remain)
    FUNCTION check_room_conflict(
        p_room_id       IN NUMBER,
        p_start_time    IN TIMESTAMP,
        p_end_time      IN TIMESTAMP,
        p_session_id    IN NUMBER DEFAULT NULL
    ) RETURN VARCHAR2;
    
    FUNCTION get_session_occupancy(
        p_session_id IN NUMBER
    ) RETURN NUMBER;
    
    FUNCTION is_session_full(
        p_session_id IN NUMBER
    ) RETURN BOOLEAN;
    
    FUNCTION generate_session_qr(
        p_session_id IN NUMBER
    ) RETURN VARCHAR2;
    
    FUNCTION get_speaker_session_count(
        p_speaker_id IN NUMBER
    ) RETURN NUMBER;
    
    PROCEDURE register_attendee(
        p_attendee_id   IN NUMBER,
        p_session_id    IN NUMBER,
        p_success       OUT BOOLEAN,
        p_message       OUT VARCHAR2
    );
    
    PROCEDURE cancel_registration(
        p_attendee_id   IN NUMBER,
        p_session_id    IN NUMBER
    );
    
    PROCEDURE checkin_attendee(
        p_attendee_id   IN NUMBER,
        p_session_id    IN NUMBER,
        p_success       OUT BOOLEAN,
        p_message       OUT VARCHAR2
    );
    
    FUNCTION validate_speaker_schedule(
        p_speaker_id    IN NUMBER,
        p_start_time    IN TIMESTAMP,
        p_end_time      IN TIMESTAMP,
        p_session_id    IN NUMBER DEFAULT NULL
    ) RETURN VARCHAR2;
    
    -- NEW RATING FUNCTIONS
    FUNCTION get_session_avg_rating(
        p_session_id IN NUMBER
    ) RETURN NUMBER;
    
    FUNCTION get_session_rating_count(
        p_session_id IN NUMBER
    ) RETURN NUMBER;
    
    FUNCTION get_speaker_avg_rating(
        p_speaker_id IN NUMBER
    ) RETURN NUMBER;
    
    PROCEDURE submit_session_rating(
        p_session_id        IN NUMBER,
        p_attendee_id       IN NUMBER,
        p_rating            IN NUMBER,
        p_comment           IN VARCHAR2 DEFAULT NULL,
        p_would_recommend   IN VARCHAR2 DEFAULT 'Y',
        p_success           OUT BOOLEAN,
        p_message           OUT VARCHAR2
    );
    
END conference_pkg;
/

CREATE OR REPLACE PACKAGE BODY conference_pkg AS

    -- ========================================================================
    -- Existing functions (body remains the same)
    -- ========================================================================
    FUNCTION check_room_conflict(
        p_room_id       IN NUMBER,
        p_start_time    IN TIMESTAMP,
        p_end_time      IN TIMESTAMP,
        p_session_id    IN NUMBER DEFAULT NULL
    ) RETURN VARCHAR2
    IS
        v_conflict_count NUMBER;
        v_conflict_session VARCHAR2(200);
    BEGIN
        SELECT COUNT(*), MAX(title)
        INTO v_conflict_count, v_conflict_session
        FROM sessions
        WHERE room_id = p_room_id
        AND session_id != NVL(p_session_id, -1)
        AND status != 'CANCELLED'
        AND (
            (p_start_time >= start_time AND p_start_time < end_time)
            OR (p_end_time > start_time AND p_end_time <= end_time)
            OR (p_start_time <= start_time AND p_end_time >= end_time)
        );
        
        IF v_conflict_count > 0 THEN
            RETURN 'CONFLICT: Room is booked for "' || v_conflict_session || '"';
        ELSE
            RETURN 'OK';
        END IF;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 'ERROR: ' || SQLERRM;
    END check_room_conflict;

    FUNCTION get_session_occupancy(p_session_id IN NUMBER) RETURN NUMBER
    IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM attendee_sessions WHERE session_id = p_session_id;
        RETURN v_count;
    EXCEPTION
        WHEN OTHERS THEN RETURN 0;
    END get_session_occupancy;

    FUNCTION is_session_full(p_session_id IN NUMBER) RETURN BOOLEAN
    IS
        v_max_attendees NUMBER;
        v_current_count NUMBER;
    BEGIN
        SELECT s.max_attendees, COUNT(ats.attendee_session_id)
        INTO v_max_attendees, v_current_count
        FROM sessions s
        LEFT JOIN attendee_sessions ats ON s.session_id = ats.session_id
        WHERE s.session_id = p_session_id
        GROUP BY s.max_attendees;
        
        IF v_max_attendees IS NULL THEN RETURN FALSE; END IF;
        RETURN v_current_count >= v_max_attendees;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN FALSE;
        WHEN OTHERS THEN RETURN FALSE;
    END is_session_full;

    FUNCTION generate_session_qr(p_session_id IN NUMBER) RETURN VARCHAR2
    IS
        v_qr_data VARCHAR2(500);
    BEGIN
        SELECT 'CONF2025|SESSION|' || session_id || '|' || session_code
        INTO v_qr_data FROM sessions WHERE session_id = p_session_id;
        RETURN v_qr_data;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN RETURN NULL;
        WHEN OTHERS THEN RETURN NULL;
    END generate_session_qr;

    FUNCTION get_speaker_session_count(p_speaker_id IN NUMBER) RETURN NUMBER
    IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_count FROM sessions 
        WHERE speaker_id = p_speaker_id AND status != 'CANCELLED';
        RETURN v_count;
    EXCEPTION
        WHEN OTHERS THEN RETURN 0;
    END get_speaker_session_count;

    PROCEDURE register_attendee(
        p_attendee_id IN NUMBER, p_session_id IN NUMBER,
        p_success OUT BOOLEAN, p_message OUT VARCHAR2)
    IS
        v_already_registered NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_already_registered FROM attendee_sessions
        WHERE attendee_id = p_attendee_id AND session_id = p_session_id;
        
        IF v_already_registered > 0 THEN
            p_success := FALSE; p_message := 'Already registered'; RETURN;
        END IF;
        
        IF is_session_full(p_session_id) THEN
            p_success := FALSE; p_message := 'Session is full'; RETURN;
        END IF;
        
        INSERT INTO attendee_sessions (attendee_id, session_id)
        VALUES (p_attendee_id, p_session_id);
        p_success := TRUE; p_message := 'Successfully registered';
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK; p_success := FALSE; p_message := 'Error: ' || SQLERRM;
    END register_attendee;

    PROCEDURE cancel_registration(p_attendee_id IN NUMBER, p_session_id IN NUMBER)
    IS
    BEGIN
        DELETE FROM attendee_sessions
        WHERE attendee_id = p_attendee_id AND session_id = p_session_id;
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN ROLLBACK; RAISE;
    END cancel_registration;

    PROCEDURE checkin_attendee(
        p_attendee_id IN NUMBER, p_session_id IN NUMBER,
        p_success OUT BOOLEAN, p_message OUT VARCHAR2)
    IS
        v_registered NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_registered FROM attendee_sessions
        WHERE attendee_id = p_attendee_id AND session_id = p_session_id;
        
        IF v_registered = 0 THEN
            p_success := FALSE; p_message := 'Not registered'; RETURN;
        END IF;
        
        UPDATE attendee_sessions
        SET attended = 'Y', check_in_time = SYSTIMESTAMP
        WHERE attendee_id = p_attendee_id AND session_id = p_session_id;
        
        p_success := TRUE; p_message := 'Checked in successfully';
        COMMIT;
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK; p_success := FALSE; p_message := 'Error: ' || SQLERRM;
    END checkin_attendee;

    FUNCTION validate_speaker_schedule(
        p_speaker_id IN NUMBER, p_start_time IN TIMESTAMP,
        p_end_time IN TIMESTAMP, p_session_id IN NUMBER DEFAULT NULL)
    RETURN VARCHAR2
    IS
        v_conflict_count NUMBER;
        v_conflict_session VARCHAR2(200);
    BEGIN
        SELECT COUNT(*), MAX(title)
        INTO v_conflict_count, v_conflict_session
        FROM sessions
        WHERE speaker_id = p_speaker_id
        AND session_id != NVL(p_session_id, -1)
        AND status != 'CANCELLED'
        AND (
            (p_start_time >= start_time AND p_start_time < end_time)
            OR (p_end_time > start_time AND p_end_time <= end_time)
            OR (p_start_time <= start_time AND p_end_time >= end_time)
        );
        
        IF v_conflict_count > 0 THEN
            RETURN 'CONFLICT: Speaker has "' || v_conflict_session || '" at this time';
        ELSE
            RETURN 'OK';
        END IF;
    EXCEPTION
        WHEN OTHERS THEN RETURN 'ERROR: ' || SQLERRM;
    END validate_speaker_schedule;

    -- ========================================================================
    -- NEW RATING FUNCTIONS
    -- ========================================================================
    
    FUNCTION get_session_avg_rating(
        p_session_id IN NUMBER
    ) RETURN NUMBER
    IS
        v_avg NUMBER;
    BEGIN
        SELECT ROUND(AVG(rating), 1)
        INTO v_avg
        FROM session_ratings
        WHERE session_id = p_session_id;
        
        RETURN NVL(v_avg, 0);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0;
        WHEN OTHERS THEN
            RETURN 0;
    END get_session_avg_rating;
    
    FUNCTION get_session_rating_count(
        p_session_id IN NUMBER
    ) RETURN NUMBER
    IS
        v_count NUMBER;
    BEGIN
        SELECT COUNT(*)
        INTO v_count
        FROM session_ratings
        WHERE session_id = p_session_id;
        
        RETURN v_count;
    EXCEPTION
        WHEN OTHERS THEN
            RETURN 0;
    END get_session_rating_count;
    
    FUNCTION get_speaker_avg_rating(
        p_speaker_id IN NUMBER
    ) RETURN NUMBER
    IS
        v_avg NUMBER;
    BEGIN
        SELECT ROUND(AVG(sr.rating), 1)
        INTO v_avg
        FROM session_ratings sr
        JOIN sessions s ON sr.session_id = s.session_id
        WHERE s.speaker_id = p_speaker_id;
        
        RETURN NVL(v_avg, 0);
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0;
        WHEN OTHERS THEN
            RETURN 0;
    END get_speaker_avg_rating;
    
    PROCEDURE submit_session_rating(
        p_session_id        IN NUMBER,
        p_attendee_id       IN NUMBER,
        p_rating            IN NUMBER,
        p_comment           IN VARCHAR2 DEFAULT NULL,
        p_would_recommend   IN VARCHAR2 DEFAULT 'Y',
        p_success           OUT BOOLEAN,
        p_message           OUT VARCHAR2
    )
    IS
        v_attended NUMBER;
        v_existing_rating NUMBER;
    BEGIN
        -- Verify attendee attended the session
        SELECT COUNT(*)
        INTO v_attended
        FROM attendee_sessions
        WHERE attendee_id = p_attendee_id
        AND session_id = p_session_id
        AND attended = 'Y';
        
        IF v_attended = 0 THEN
            p_success := FALSE;
            p_message := 'You must attend the session before rating it';
            RETURN;
        END IF;
        
        -- Check if already rated
        SELECT COUNT(*)
        INTO v_existing_rating
        FROM session_ratings
        WHERE attendee_id = p_attendee_id
        AND session_id = p_session_id;
        
        IF v_existing_rating > 0 THEN
            -- Update existing rating
            UPDATE session_ratings
            SET rating = p_rating,
                comment = p_comment,
                would_recommend = p_would_recommend,
                rating_date = SYSDATE
            WHERE attendee_id = p_attendee_id
            AND session_id = p_session_id;
            
            p_success := TRUE;
            p_message := 'Rating updated successfully';
        ELSE
            -- Insert new rating
            INSERT INTO session_ratings (
                session_id, attendee_id, rating, comment, would_recommend
            ) VALUES (
                p_session_id, p_attendee_id, p_rating, p_comment, p_would_recommend
            );
            
            p_success := TRUE;
            p_message := 'Rating submitted successfully';
        END IF;
        
        COMMIT;
        
    EXCEPTION
        WHEN OTHERS THEN
            ROLLBACK;
            p_success := FALSE;
            p_message := 'Error: ' || SQLERRM;
    END submit_session_rating;

END conference_pkg;
/

PROMPT   ... package extended with rating functions

-- ============================================================================
-- Create Rating View
-- ============================================================================
PROMPT
PROMPT Creating ratings view...

CREATE OR REPLACE VIEW v_session_ratings AS
SELECT 
    s.session_id,
    s.session_code,
    s.title as session_title,
    sp.speaker_id,
    sp.first_name || ' ' || sp.last_name as speaker_name,
    conference_pkg.get_session_avg_rating(s.session_id) as avg_rating,
    conference_pkg.get_session_rating_count(s.session_id) as rating_count,
    ROUND(
        (SELECT COUNT(*) * 100.0 / NULLIF(COUNT(*), 0)
         FROM session_ratings sr
         WHERE sr.session_id = s.session_id
         AND sr.would_recommend = 'Y'), 0
    ) as recommend_percentage
FROM sessions s
JOIN speakers sp ON s.speaker_id = sp.speaker_id
WHERE s.status = 'COMPLETED';

COMMENT ON VIEW v_session_ratings IS 'Summary of session ratings and recommendations';

PROMPT   ... ratings view created

-- ============================================================================
-- Add Sample Ratings (for demo purposes)
-- ============================================================================
PROMPT
PROMPT Adding sample ratings...

-- Rate the keynote session
INSERT INTO session_ratings (session_id, attendee_id, rating, comment, would_recommend)
SELECT s.session_id, 1, 5, 'Outstanding keynote! Very inspiring and practical insights.', 'Y'
FROM sessions s WHERE s.session_code = 'KEY001';

INSERT INTO session_ratings (session_id, attendee_id, rating, comment, would_recommend)
SELECT s.session_id, 2, 5, 'Best keynote I have attended in years. Great demos!', 'Y'
FROM sessions s WHERE s.session_code = 'KEY001';

INSERT INTO session_ratings (session_id, attendee_id, rating, comment, would_recommend)
SELECT s.session_id, 9, 4, 'Really good content, would have liked more time for Q&A.', 'Y'
FROM sessions s WHERE s.session_code = 'KEY001';

-- Rate performance tuning session
INSERT INTO session_ratings (session_id, attendee_id, rating, comment, would_recommend)
SELECT s.session_id, 1, 5, 'Excellent deep dive! Learned techniques I can use immediately.', 'Y'
FROM sessions s WHERE s.session_code = 'S101';

-- Rate the "Building APEX Without Builder" session
INSERT INTO session_ratings (session_id, attendee_id, rating, comment, would_recommend)
SELECT s.session_id, 1, 5, 'Mind-blowing approach! This changes everything.', 'Y'
FROM sessions s WHERE s.session_code = 'S204';

INSERT INTO session_ratings (session_id, attendee_id, rating, comment, would_recommend)
SELECT s.session_id, 2, 5, 'Revolutionary! Cannot wait to try this on my projects.', 'Y'
FROM sessions s WHERE s.session_code = 'S204';

INSERT INTO session_ratings (session_id, attendee_id, rating, comment, would_recommend)
SELECT s.session_id, 3, 4, 'Great concept, though I think the Builder still has its place.', 'Y'
FROM sessions s WHERE s.session_code = 'S204';

COMMIT;

PROMPT   ... sample ratings added

-- ============================================================================
-- Add Ratings Page to APEX Application
-- ============================================================================
PROMPT
PROMPT Adding ratings dashboard page to APEX app...

BEGIN
    -- Page 30: Ratings Dashboard
    wwv_flow_api.create_page(
        p_id              => 30,
        p_flow_id         => 200,
        p_name            => 'Session Ratings',
        p_alias           => 'SESSION_RATINGS',
        p_step_title      => 'Session Ratings Dashboard',
        p_autocomplete_on_off => 'OFF',
        p_page_template_options => '#DEFAULT#',
        p_protection_level => 'C',
        p_help_text       => 'View ratings and feedback for all completed sessions.');
        
    -- Region: Top Rated Sessions
    wwv_flow_api.create_page_plug(
        p_id                  => wwv_flow_api.id('TOP_RATED'),
        p_flow_id             => 200,
        p_page_id             => 30,
        p_plug_name           => 'Top Rated Sessions',
        p_region_template_options => '#DEFAULT#:t-Region--scrollBody',
        p_plug_template       => wwv_flow_api.id(0),
        p_plug_display_sequence => 10,
        p_plug_display_point  => 'BODY',
        p_query_type          => 'SQL',
        p_plug_source         => q'[
SELECT 
    session_code,
    session_title,
    speaker_name,
    avg_rating,
    rating_count,
    recommend_percentage,
    CASE 
        WHEN avg_rating >= 4.5 THEN '★★★★★'
        WHEN avg_rating >= 3.5 THEN '★★★★☆'
        WHEN avg_rating >= 2.5 THEN '★★★☆☆'
        WHEN avg_rating >= 1.5 THEN '★★☆☆☆'
        ELSE '★☆☆☆☆'
    END as stars
FROM v_session_ratings
WHERE rating_count > 0
ORDER BY avg_rating DESC, rating_count DESC
        ]',
        p_plug_source_type    => 'NATIVE_IR',
        p_plug_query_options  => 'DERIVED_REPORT_COLUMNS');
        
    -- Region: Speaker Ratings
    wwv_flow_api.create_page_plug(
        p_id                  => wwv_flow_api.id('SPEAKER_RATINGS'),
        p_flow_id             => 200,
        p_page_id             => 30,
        p_plug_name           => 'Speaker Average Ratings',
        p_region_template_options => '#DEFAULT#:t-Region--scrollBody',
        p_plug_template       => wwv_flow_api.id(0),
        p_plug_display_sequence => 20,
        p_plug_display_point  => 'BODY',
        p_query_type          => 'SQL',
        p_plug_source         => q'[
SELECT 
    sp.first_name || ' ' || sp.last_name as speaker,
    sp.company,
    conference_pkg.get_speaker_avg_rating(sp.speaker_id) as avg_rating,
    COUNT(sr.rating_id) as total_ratings,
    ROUND(AVG(sr.rating), 2) as calculated_avg
FROM speakers sp
JOIN sessions s ON sp.speaker_id = s.speaker_id
LEFT JOIN session_ratings sr ON s.session_id = sr.session_id
WHERE s.status = 'COMPLETED'
GROUP BY sp.speaker_id, sp.first_name, sp.last_name, sp.company
HAVING COUNT(sr.rating_id) > 0
ORDER BY calculated_avg DESC
        ]',
        p_plug_source_type    => 'NATIVE_JET_CHART');
        
END;
/

COMMIT;

PROMPT
PROMPT ========================================
PROMPT Session Ratings Feature Added!
PROMPT ========================================
PROMPT
PROMPT New Components:
PROMPT   - TABLE: session_ratings
PROMPT   - FUNCTIONS: get_session_avg_rating, get_session_rating_count, get_speaker_avg_rating
PROMPT   - PROCEDURE: submit_session_rating
PROMPT   - VIEW: v_session_ratings
PROMPT   - APEX PAGE: 30 (Session Ratings Dashboard)
PROMPT
PROMPT Sample Data:
PROMPT   - 7 ratings added for demo sessions
PROMPT
PROMPT *** FEATURE ADDED IN < 2 MINUTES ***
PROMPT *** ENTIRELY AI-GENERATED ***
PROMPT ========================================
PROMPT
PROMPT Access new page: [Your APEX URL]/r/conf_tracker/session-ratings
PROMPT ========================================
